---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mvsd-demo-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deployment
  labels:
    app: demo-app
spec:
  selector:
    matchLabels:
      app: demo-app-pod
  replicas: 1
  template:
    metadata:
      name: demo-app-pod
      labels:
        app: demo-app-pod
    spec:
      serviceAccountName: mvsd-demo-app
      imagePullSecrets:
        - name: dockercred
      containers:
        - name: demo-app
          image: siakag/mongo-vault-secrets-demo:1.0.0
          imagePullPolicy: Always
